package application.controller.enums;

public enum SessionRequestResult {
  SESSION_REQUEST_TRUE,
  SESSION_REQUEST_FALSE,
  END_SESSION_REQUEST_SUCCESS,
  END_SESSION_REQUEST_FAILED,
  FAILED_BY_NETWORK,
  FAILED_BY_UNKNOWN_ERROR
}
