package application.controller.enums;

public enum SessionRequestResult {
  SESSION_REQUEST_TRUE,
  FAILED_SESSION_SETUP,
  FAILED_BY_TUTOR_NOT_ONLINE,
  FAILED_BY_TUTOR_NOT_LIVE,
  END_SESSION_REQUEST_SUCCESS,
  END_SESSION_REQUEST_FAILED,
  FAILED_BY_NETWORK,
  FAILED_BY_UNKNOWN_ERROR;
}
