package application.controller.enums;

public enum WhiteboardRenderResult {
  WHITEBOARD_RENDER_SUCCESS,
  FAILED_BY_NETWORK,
  FAILED_BY_UNEXPECTED_ERROR,
  FAILED_BY_INCORRECT_STREAM_ID,
  FAILED_BY_INCORRECT_USER_ID;
}
